Repository prgrms-web-devcourse/slam-client, pull requests merged in 2021-12, with the labels that each got.

#2 Feature/login/kakaologin
  .eslintrc.json
  components/KaKaoLogin/index.tsx
  components/KaKaoLogin/loadSdk.ts
  components/KaKaoLogin/types.ts
  pages/login/index.tsx
Labels: 기능

#25 12월 8일 배포 2차
  src/pages/_app.tsx
Labels: 배포

#20 Feat/map/map-ui
  package.json
  src/components/KakaoMap/index.tsx
  src/components/base/ModalSheet/index.tsx
  src/components/base/index.ts
  src/components/domain/DatePicker/DateItem.tsx
  src/components/domain/DatePicker/index.tsx
  src/components/domain/SlotPicker/SlotItem.tsx
  src/components/domain/SlotPicker/index.tsx
  src/components/domain/SlotPicker/types.tsx
  src/components/domain/index.ts
  src/pages/court/create.tsx
  src/pages/map/index.tsx
  yarn.lock
Labels: 기능, 구현중

#32 ✨ feat: user 페이지 기본 구조 구현
  src/contexts/NavigationProvider/actionTypes.ts
  src/contexts/NavigationProvider/context.ts
  src/contexts/NavigationProvider/index.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/contexts/NavigationProvider/types.ts
  src/pages/user/[userId]/index.tsx
Labels: 기능

#31 ✨ feat: 카카오 로그인 리다이렉팅 후 인가코드 넘기기
  src/UtilRoute/index.tsx
  src/components/domain/KakaoLogin/index.tsx
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/handles.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/contexts/NavigationProvider/reducer.ts
  src/hooks/domain/index.ts
  src/hooks/domain/useLocalToken.ts
  src/pages/login/index.tsx
  src/pages/login/redirect/index.tsx
  src/service/fetcher/index.ts
  src/service/serviceApi.ts
Labels: 기능, 구현중

#41 ✨ feat: 프로필 편집 페이지 구현
  public/assets/default_profile.svg
  src/components/base/Avatar/index.tsx
  src/components/domain/RadioInput/RadioItem.tsx
  src/components/domain/RadioInput/index.tsx
  src/components/domain/UserInfoPicker/PositionsPicker.tsx
  src/components/domain/UserInfoPicker/ProficiencyPicker.tsx
  src/components/domain/UserInfoPicker/index.tsx
  src/components/domain/UserInfoPicker/types.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/pages/user/edit/index.tsx
Labels: 기능

#42 Feat/reservations
  src/components/Reservations/CompletedReservations/index.tsx
  src/components/Reservations/Loudspeaker/index.tsx
  src/components/Reservations/Participants/index.tsx
  src/components/Reservations/UpcomingReservations/index.tsx
  src/pages/reservations/index.tsx
Labels: 기능, 구현중

#44 ✨ feat: CustomButton 이벤트바인딩
  src/components/domain/TopNavigation/index.tsx
  src/contexts/NavigationProvider/actionTypes.ts
  src/contexts/NavigationProvider/context.ts
  src/contexts/NavigationProvider/index.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/contexts/NavigationProvider/types.ts
  src/pages/login/index.tsx
Labels: 기능

#37 ✨feat: 사용자정보 request시 로띠 활용 400ms 페이드아웃 로딩
  package.json
  src/UtilRoute/index.tsx
  src/components/domain/AuthLoading.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/domain/index.ts
  src/components/layout/DefaultLayout/index.tsx
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/NavigationProvider/index.tsx
  src/contexts/hooks.ts
  src/pages/_document.tsx
  src/pages/login/index.tsx
  src/pages/login/redirect/index.tsx
  tsconfig.json
  yarn.lock
Labels: 기능

#36 ✨feat: 소켓 프로바이더 (Sockjs + Stomp 프로토콜) 설정
  package.json
  src/contexts/AuthProvider/index.tsx
  src/contexts/Providers.tsx
  src/contexts/SocketProvider/context.ts
  src/contexts/SocketProvider/hook.ts
  src/contexts/SocketProvider/index.tsx
  src/contexts/SocketProvider/useStomp.ts
  src/contexts/index.ts
  src/pages/notifications/index.tsx
  src/service/index.ts
  src/service/socketApi.ts
  yarn.lock
Labels: 기능

#61 ♻️ refactor: spacer 컴포넌트 리팩토링
  src/components/base/Spacer/index.tsx
  src/components/domain/Favorites/index.tsx
  src/pages/courts/create.tsx
  src/pages/hanna/index.tsx
  src/pages/index.tsx
  src/pages/user/edit/index.tsx
Labels: 리팩토링

#57 ✨ feat: IconButton, IconToggle 컴포넌트
  src/components/base/Icon/index.tsx
  src/components/base/IconButton/index.tsx
  src/components/base/IconToggle/index.tsx
  src/components/base/index.ts
Labels: 기능

#68 :recycle: refactor: 소켓 프로바이더 리팩토링 / 로그인 하지 않은 사용자의 경우 소켓연결 시도 방지
  src/contexts/SocketProvider/index.tsx
  src/contexts/SocketProvider/useStomp/index.ts
  src/contexts/SocketProvider/useStomp/type.ts
Labels: 개선

#69 ✨ feat: 로그아웃 추가
  src/components/base/Button/index.tsx
  src/components/base/Modal/index.tsx
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/pages/user/menu/index.tsx
Labels: 기능

#82 💄 style: 로그인 페이지 스타일링
  src/components/base/Button/index.tsx
  src/components/domain/BottomFixedButton/index.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/Logo/index.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/AuthLoading.tsx
  src/contexts/AuthProvider/index.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/pages/login/index.tsx
  src/styles/theme.ts
Labels: 디자인

#76 💄 style: Input 컴포넌트 스타일링
  src/components/base/Input/index.tsx
  src/pages/user/edit/index.tsx
Labels: 디자인

#79 ♻️ refactor: reservations 확성기 컴포넌트 리팩토링
  src/components/Reservations/CompletedReservations/index.tsx
  src/components/Reservations/Loudspeaker/index.tsx
  src/components/Reservations/UpcomingReservations/index.tsx
  src/pages/reservations/index.tsx
Labels: 리팩토링

#89 ✨ feat: Map Marker 이미지 연결
  public/assets/basketball-fire.gif
  public/assets/basketball-pause.png
  public/assets/basketball-transparent.gif
  public/assets/basketball/animation_off_400.png
  public/assets/basketball/fire_off_400.gif
  public/assets/basketball/fire_on_400.gif
  src/components/domain/KakaoMapMarker/BasketballMarker.tsx
Labels: 개선

#90 ✨ feat: Notifications mock 데이터를 넣고 컴포넌트로 분리
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/NotificationList/index.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/pages/notifications/index.tsx
Labels: 기능

#91 ♻️ refactor: 공유, 채팅, 즐겨찾기, 지도 버튼 domain 공통 컴포넌트로 분리
  src/components/Reservations/CompletedReservations/index.tsx
  src/components/Reservations/UpcomingReservations/index.tsx
  src/components/base/Button/index.tsx
  src/components/base/Icon/index.tsx
  src/components/base/IconButton/index.tsx
  src/components/base/IconToggle/index.tsx
  src/components/base/ModalSheet/index.tsx
  src/components/base/Text/index.tsx
  src/components/domain/CourtItem/Address.tsx
  src/components/domain/CourtItem/ChatLink.tsx
  src/components/domain/CourtItem/Datetime.tsx
  src/components/domain/CourtItem/FavoritesToggle.tsx
  src/components/domain/CourtItem/Header.tsx
  src/components/domain/CourtItem/KakaoMapLink.tsx
  src/components/domain/CourtItem/ShareButton.tsx
  src/components/domain/CourtItem/index.tsx
  src/components/domain/CourtItem/style.tsx
  src/components/domain/Favorites/index.tsx
  src/components/domain/KakaoMapMarker/BasketballMarker.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/pages/courts/index.tsx
  src/pages/index.tsx
  src/pages/reservations/index.tsx
  src/styles/theme.ts
Labels: 기능

#93 Feat/notifications/notification list
  src/components/base/Avatar/index.tsx
  src/components/base/LinkStrong/index.tsx
  src/components/base/index.ts
  src/components/domain/LinkAvatar/index.tsx
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/NotificationList/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/NavigationProvider/reducer.ts
  src/contexts/SocketProvider/context.ts
  src/contexts/SocketProvider/index.tsx
  src/contexts/SocketProvider/useStomp/index.ts
  src/contexts/SocketProvider/useStomp/utils.ts
  src/pages/notifications/index.tsx
Labels: 기능

#96 ✨ feat: 선택한 시간대로 예약 페이지 스크롤 포지션 설정
  src/components/domain/TimeTable/TimeBlockUnits/Hour.tsx
  src/components/domain/TimeTable/TimeBlockUnits/style.tsx
  src/components/domain/TimeTable/index.tsx
  src/components/layout/DefaultLayout/Container.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
Labels: 기능

#95 ✨ feat: 관리자용 새 농구장 리스트 조회 페이지
  src/components/domain/NewCourtItem/index.tsx
  src/components/domain/NewCourtItem/types.ts
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/index.ts
  src/contexts/NavigationProvider/actionTypes.ts
  src/contexts/NavigationProvider/reducer.ts
  src/pages/admin/newcourts.tsx
Labels: 기능

#94 🚸 improve: 프로필 편집 페이지 스타일링 및 기능 개선
  src/components/domain/ValidationNoticeBar/index.tsx
  src/components/domain/index.ts
  src/contexts/NavigationProvider/reducer.ts
  src/pages/user/edit/index.tsx
Labels: 개선, 디자인

#100 🚸 improve: 프로필 페이지 수정 및 스타일 작업
  src/components/base/Button/index.tsx
  src/components/base/Chip/index.tsx
  src/components/base/RadioInput/RadioItem.tsx
  src/components/base/index.ts
  src/components/domain/ProfileFavoritesListItem/index.tsx
  src/components/domain/UserInfoPicker/types.tsx
  src/components/domain/index.ts
  src/pages/user/[userId]/index.tsx
  src/styles/global.css
Labels: 개선, 디자인

#106 💄style: 농구장 예약 현황 페이지 스타일링
  public/assets/pond.svg
  src/components/base/Modal/index.tsx
  src/components/base/ModalSheet/index.tsx
  src/components/domain/BottomFixedButton/index.tsx
  src/components/domain/Modal/index.tsx
  src/components/domain/Modal/style.tsx
  src/components/domain/ReservationModalContent/BlockStatus.tsx
  src/components/domain/ReservationModalContent/ExistedReservation.tsx
  src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
  src/components/domain/ReservationModalContent/SelectedRange.tsx
  src/components/domain/ReservationModalContent/StepTwoCommonContent.tsx
  src/components/domain/ReservationModalContent/style.tsx
  src/components/domain/TimeTable/TimeBlockUnits/ActionTimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/Header.tsx
  src/components/domain/TimeTable/TimeBlockUnits/TimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/index.tsx
  src/components/domain/TimeTable/TimeBlockUnits/style.tsx
  src/components/domain/TimeTable/TimeRangeSelector/index.tsx
  src/components/domain/TimeTable/index.tsx
  src/components/domain/TimeTable/style.tsx
  src/components/domain/index.ts
  src/contexts/NavigationProvider/actionTypes.ts
  src/contexts/NavigationProvider/context.ts
  src/contexts/NavigationProvider/index.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/contexts/SocketProvider/index.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
  src/pages/user/menu/index.tsx
Labels: 기능, 디자인

#112 Feat/user/api
  src/UtilRoute/index.tsx
  src/components/domain/index.ts
  src/pages/user/[userId]/index.tsx
  src/service/userApi.ts
  src/utils/userInfo.ts
Labels: 버그

#113 Feat/notifications/notification list
  package.json
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/NotificationList/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  tsconfig.json
  yarn.lock
Labels: 기능

#103 💄style: 새 농구장 추가 페이지 스타일 작업
  public/assets/preview_map.png
  src/components/base/Input/index.tsx
  src/components/domain/BottomFixedButton/index.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/pages/courts/create.tsx
Labels: 개선, 디자인

#117 🐛 fix: 유저페이지 자신과 다른 사람을 구별
  src/pages/user/[userId]/index.tsx
Labels: 기능

#122 ✨ feat: 유저페이지 팔로우 소켓 연결 (백엔드와 테스트 완료)
  src/components/domain/UserInfoPicker/types.tsx
  src/contexts/AuthProvider/index.tsx
  src/contexts/SocketProvider/context.ts
  src/contexts/SocketProvider/index.tsx
  src/contexts/SocketProvider/useStomp/index.ts
  src/pages/notifications/index.tsx
  src/pages/reservations/index.tsx
  src/pages/user/[userId]/index.tsx
  src/utils/userInfo.ts
Labels: 디자인

#124 ✨ feat: 농구장, 예약 api 연동
  src/components/domain/DatePicker/index.tsx
  src/components/domain/KakaoMap/index.tsx
  src/components/domain/KakaoMapMarker/BasketballMarker.tsx
  src/components/domain/KakaoMapMarker/GeneralMarker.tsx
  src/components/domain/TimeTable/index.tsx
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
  src/pages/reservations/index.tsx
  src/service/courtApi.ts
  src/service/index.ts
  src/service/reservationApi.ts
Labels: 기능

#132 💄 style: 각 요소의 hover 스타일링
  src/components/base/Button/index.tsx
  src/components/base/RadioInput/RadioItem.tsx
  src/components/base/Text/index.tsx
  src/components/domain/DatePicker/DateItem.tsx
Labels: 디자인

#140 ✨ feat: 프로필 편집 페이지 api 연동
  src/components/domain/ProfileForm/index.tsx
  src/components/domain/UserInfoPicker/types.tsx
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/hooks/useForm.ts
  src/pages/user/edit/index.tsx
  src/service/userApi.ts
Labels: 기능

#142 🐛 fix: UtilRoute 기본 privateRedirectPath 변경 #138
  src/UtilRoute/index.tsx
Labels: 개선

#143 💄style: 관리자 페이지 스타일 작업
  src/components/base/Tab/TabItem.tsx
  src/components/base/Tab/index.tsx
  src/components/domain/NewCourtItem/index.tsx
  src/pages/admin/newcourts.tsx
Labels: 디자인

#147 하단 네비게이션 관리자 버튼 추가 #144
  src/components/domain/BottomNavigtion/NavIcon/index.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
Labels: 개선

#146 🐛 fix: 지나간 시간에 대한 예약 및 지도뷰 조회 비활성화
  src/components/base/RadioInput/RadioItem.tsx
  src/components/domain/DatePicker/DateItem.tsx
  src/components/domain/SlotPicker/index.tsx
  src/components/domain/TimeTable/TimeBlockUnits/ActionTimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/TimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/style.tsx
  src/components/domain/TimeTable/TimeRangeSelector/index.tsx
  src/components/domain/TimeTable/index.tsx
  src/components/domain/TimeTable/style.tsx
  src/components/domain/TimeTable/type.ts
  src/components/domain/index.ts
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
  src/service/reservationApi.ts
  src/utils/timeTable.ts
Labels: 기능

#149 배포
  public/assets/lottie/loader-basketball.json
  src/UtilRoute/index.tsx
  src/components/base/RadioInput/RadioItem.tsx
  src/components/base/Tab/TabItem.tsx
  src/components/base/Tab/index.tsx
  src/components/domain/BasketballLoading/LoaderBasketball/index.tsx
  src/components/domain/BasketballLoading/index.tsx
  src/components/domain/BottomFixedButton/index.tsx
  src/components/domain/BottomNavigtion/NavIcon/index.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/DatePicker/DateItem.tsx
  src/components/domain/LeadToLoginModal/index.tsx
  src/components/domain/NewCourtItem/index.tsx
  src/components/domain/ProfileForm/index.tsx
  src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
  src/components/domain/SlotPicker/index.tsx
  src/components/domain/TimeTable/TimeBlockUnits/ActionTimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/TimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/style.tsx
  src/components/domain/TimeTable/TimeRangeSelector/index.tsx
  src/components/domain/TimeTable/index.tsx
  src/components/domain/TimeTable/style.tsx
  src/components/domain/TimeTable/type.ts
  src/components/domain/UserInfoPicker/types.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/hooks/useForm.ts
  src/pages/admin/newcourts.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/create.tsx
  src/pages/courts/index.tsx
  src/pages/reservations/index.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/service/courtApi.ts
  src/service/reservationApi.ts
  src/service/userApi.ts
  src/utils/timeTable.ts
Labels: 배포

#151 ✨feat: 쿼리스트링 여부에 따른 지도 center restore
  src/pages/courts/index.tsx
Labels: 기능

#155 ✨ feat: 농구장 즐겨찾기 / 예약 태그 PNG, GIF 지도에 추가 #154
  src/components/domain/KakaoMapMarker/BasketballMarker.tsx
Labels: 리뷰 요청, 개선, 디자인

#153 탐색 경유 로그인 유도를 위한 로그인페이지 BottomFixedButton 개선
  src/components/domain/BottomFixedButton/index.tsx
  src/pages/login/index.tsx
  src/styles/theme.ts
Labels: 리뷰 요청, 개선, 리팩토링

#156 배포
  public/assets/basketball/animation_off_favorited.png
  public/assets/basketball/fire_off_all_tagged.gif
  public/assets/basketball/fire_off_favorited.gif
  public/assets/basketball/fire_off_reservated.gif
  public/assets/basketball/fire_on_all_tagged.gif
  public/assets/basketball/fire_on_favorited.gif
  public/assets/basketball/fire_on_reservated.gif
  public/assets/favorited.svg
  public/assets/reservated.svg
  src/components/base/Button/index.tsx
  src/components/domain/BottomFixedButton/index.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/Favorites/index.tsx
  src/components/domain/KakaoMapMarker/BasketballMarker.tsx
  src/components/domain/NoItemMessage/index.tsx
  src/contexts/AuthProvider/AuthLoading.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/pages/courts/index.tsx
  src/pages/login/index.tsx
  src/pages/reservations/index.tsx
  src/styles/theme.ts
Labels: 배포

#159 무한 스크롤 및 실시간 알림 구현 #158
  src/components/domain/NoItemMessage/index.tsx
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/NotificationList/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/contexts/SocketProvider/useStomp/index.ts
  src/hooks/index.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/notifications/index.tsx
  src/pages/user/[userId]/index.tsx
  src/service/index.ts
  src/service/notificationApi.ts
  src/styles/theme.ts
Labels: 기능

#160 배포
  src/components/base/Avatar/index.tsx
  src/components/base/Button/index.tsx
  src/components/domain/BottomFixedButton/index.tsx
  src/components/domain/KakaoMap/index.tsx
  src/components/domain/NoItemMessage/index.tsx
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/NotificationList/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/contexts/SocketProvider/useStomp/index.ts
  src/hooks/index.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/create.tsx
  src/pages/courts/index.tsx
  src/pages/notifications/index.tsx
  src/pages/user/[userId]/index.tsx
  src/service/courtApi.ts
  src/service/index.ts
  src/service/notificationApi.ts
  src/styles/theme.ts
Labels: 배포

#161 🚸 improve: 타임 테이블 시작과 끝 시간 선택 사용성 개선
  src/components/domain/ReservationModalContent/ExistedReservation.tsx
  src/components/domain/ReservationModalContent/ParticipantsPerTime.tsx
  src/components/domain/ReservationModalContent/SelectedRange.tsx
  src/components/domain/ReservationModalContent/SelectedTime.tsx
  src/components/domain/ReservationModalContent/StepTwoCommonContent.tsx
  src/components/domain/ReservationModalContent/TimeForm.tsx
  src/components/domain/ReservationModalContent/style.tsx
  src/components/domain/TimeTable/TimeBlockUnits/ActionTimeBlockUnit.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/reservations/index.tsx
Labels: 개선, 기능, 버그

#163 ✨ feat: 사용자가 새 농구장 정보 제출 시 confirm 모달 띄우도록 구현
  src/components/domain/LeadToLoginModal/index.tsx
  src/pages/courts/create.tsx
Labels: 기능

#164 ✨ feat: 관리자 페이지 api 연동 및 무한 스크롤
  src/components/base/Tab/index.tsx
  src/components/domain/NewCourtItem/index.tsx
  src/components/domain/NewCourtItem/types.ts
  src/components/domain/ReservationItem/Loudspeaker/index.tsx
  src/pages/admin/newcourts.tsx
  src/pages/courts/create.tsx
  src/pages/reservations/index.tsx
  src/service/managementApi.ts
Labels: 기능

#175 ✨ feat: 확성기 기능 연결
  src/components/domain/ReservationItem/Loudspeaker/index.tsx
  src/components/domain/ReservationItem/index.tsx
  src/contexts/SocketProvider/context.ts
  src/contexts/SocketProvider/index.tsx
Labels: 기능

#176 배포
  README.md
  src/components/domain/Modal/style.tsx
  src/components/domain/ProfileForm/index.tsx
  src/components/domain/ReservationItem/Loudspeaker/index.tsx
  src/components/domain/ReservationItem/index.tsx
  src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
  src/contexts/SocketProvider/context.ts
  src/contexts/SocketProvider/index.tsx
  src/hooks/useForm.ts
  src/pages/admin/newcourts.tsx
  src/pages/courts/create.tsx
Labels: 배포
