Repository prgrms-web-devcourse/slam-client, pull requests merged in 2022-01, with the labels that each got.

#182 상단 네비게이션 scroll 이벤트에서 인터섹션옵저버로 성능 최적화
  .eslintrc.json
  src/components/base/Image/index.tsx
  src/components/base/Modal/index.tsx
  src/components/base/Slider/index.tsx
  src/components/base/Upload/index.tsx
  src/components/domain/KakaoLogin/index.tsx
  src/components/domain/KakaoMap/useKakaoMapEvent.ts
  src/components/domain/LinkAvatar/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/layout/DefaultLayout/index.tsx
  src/pages/admin/newcourts.tsx
  src/pages/login/redirect/index.tsx
Labels: 개선

#203 ✅ test: time table util함수 테스트 코드 작성
  babel.config.js
  package.json
  src/utils/timeTable.test.ts
  src/utils/timeTable.ts
  tsconfig.json
  yarn.lock
Labels: 테스트

#189 알림 전체 읽음 API 연결
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/KakaoMap/index.tsx
  src/components/domain/KakaoMapMarker/GeneralMarker.tsx
  src/components/domain/NewCourtItem/types.ts
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/ProfileForm/index.tsx
  src/components/domain/UserInfoPicker/PositionsPicker.tsx
  src/components/domain/UserInfoPicker/ProficiencyPicker.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/AuthProvider/types.ts
  src/contexts/SocketProvider/useStomp/index.ts
  src/domainTypes/courts.ts
  src/domainTypes/favorites.ts
  src/domainTypes/follows.ts
  src/domainTypes/index.ts
  src/domainTypes/map.ts
  src/domainTypes/newCourts.ts
  src/domainTypes/notifications.ts
  src/domainTypes/reservations.ts
  src/domainTypes/users.ts
  src/hooks/useAsyncFn.ts
  src/hooks/useClickAway.ts
  src/hooks/useHotKey.ts
  src/hooks/useHover.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useIntervalFn.ts
  src/hooks/useResize.ts
  src/hooks/useScroll.ts
  src/hooks/useTimeoutFn.ts
  src/pages/courts/create.tsx
  src/pages/courts/index.tsx
  src/pages/notifications/index.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/service/notificationApi.ts
  src/service/notificationApi/index.ts
  src/service/notificationApi/type.ts
  src/service/userApi.ts
  src/utils/geolocation.ts
  src/utils/userInfo.ts
  tsconfig.json
Labels: 기능

#201 토스트 메시지를 위한 커스텀 훅 제작
  .eslintrc.json
  package.json
  src/components/base/Avatar/AvatarGroup.tsx
  src/components/base/Breadcrumb/index.tsx
  src/components/base/Flux/Col.tsx
  src/components/base/Flux/Row.tsx
  src/components/base/Image/index.tsx
  src/components/base/Modal/index.tsx
  src/components/base/Slider/index.tsx
  src/components/base/Tab/index.tsx
  src/components/base/Text/index.tsx
  src/components/base/index.ts
  src/components/domain/CourtItem/Datetime.tsx
  src/components/domain/KakaoMap/useKakaoMapEvent.ts
  src/components/domain/ReservationModalContent/ExistedReservation.tsx
  src/components/domain/TimeTable/TimeBlockUnits/TimeBlockUnit.tsx
  src/components/layout/DefaultLayout/Container.tsx
  src/components/layout/DefaultLayout/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/NavigationProvider/index.tsx
  src/hooks/index.ts
  src/hooks/useAsyncFn.ts
  src/hooks/useForm.ts
  src/hooks/useHotKey.ts
  src/hooks/useInterval.ts
  src/hooks/useKeyPress.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useScroll.ts
  src/hooks/useSessionStorage.ts
  src/hooks/useTimeout.ts
  src/hooks/useToast/Toast.tsx
  src/hooks/useToast/ToastItem.tsx
  src/hooks/useToast/ToastManager.tsx
  src/hooks/useToast/index.ts
  src/hooks/useToast/types.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/admin/newcourts.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/reservations/index.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/menu/index.tsx
  src/service/fetcher/interceptor/index.ts
  src/service/socketApi.ts
  src/utils/getLocalToken.ts
Labels: 기능

#230 전역 타이핑
  src/domainTypes/tobe/chat.ts
  src/domainTypes/tobe/chatroom.ts
  src/domainTypes/tobe/common.ts
  src/domainTypes/tobe/court.ts
  src/domainTypes/tobe/favorite.ts
  src/domainTypes/tobe/follow.ts
  src/domainTypes/tobe/loudspeaker.ts
  src/domainTypes/tobe/map.ts
  src/domainTypes/tobe/newCourt.ts
  src/domainTypes/tobe/notification.ts
  src/domainTypes/tobe/reservation.ts
  src/domainTypes/tobe/user.ts
  src/enums/chatType.ts
  src/enums/chatroomType.ts
  src/enums/index.ts
  src/enums/notificationType.ts
  src/enums/positionType.ts
  src/enums/proficiencyType.ts
  src/enums/roleType.ts
  src/enums/statusType.ts
  src/enums/textureType.ts
  tsconfig.json
Labels: 개선

#231 Date 객체를 dayjs 라이브러리로 변경하기
  src/components/domain/CourtItem/Datetime.tsx
  src/components/domain/DatePicker/DateItem.tsx
  src/components/domain/DatePicker/index.tsx
  src/components/domain/ReservationModalContent/ParticipantsPerTime.tsx
  src/components/domain/TimeTable/TimeBlockUnits/ActionTimeBlockUnit.tsx
  src/components/domain/TimeTable/TimeBlockUnits/TimeBlockUnit.tsx
  src/components/domain/TimeTable/index.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
  src/utils/date.test.ts
  src/utils/date.ts
  src/utils/timeTable.test.ts
  src/utils/timeTable.ts
Labels: 리팩토링

#237 즐겨찾기 별표시 누락 문제 해결
  .eslintrc.json
  package.json
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/pages/login/redirect/index.tsx
  yarn.lock
Labels: 버그
